// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package cz_go_microservices_consignment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomId             string   `protobuf:"bytes,2,opt,name=custom_id,json=customId,proto3" json:"custom_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomId() string {
	if m != nil {
		return m.CustomId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Result               bool           `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{3}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "cz.go.microservices.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "cz.go.microservices.consignment.Container")
	proto.RegisterType((*Response)(nil), "cz.go.microservices.consignment.Response")
	proto.RegisterType((*EmptyRequest)(nil), "cz.go.microservices.consignment.EmptyRequest")
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_3804bf87090b51a9) }

var fileDescriptor_3804bf87090b51a9 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4e, 0xeb, 0x30,
	0x10, 0x56, 0xfa, 0x93, 0x97, 0x4c, 0xaa, 0x4a, 0xcf, 0x8b, 0xf7, 0x22, 0xba, 0x20, 0xca, 0xaa,
	0x20, 0xc8, 0xa2, 0x9c, 0x00, 0x55, 0x08, 0x95, 0x05, 0x42, 0xe6, 0x00, 0xa8, 0x4d, 0x46, 0xc1,
	0x52, 0x62, 0x07, 0x8f, 0x53, 0x04, 0xa7, 0x63, 0xc1, 0x2d, 0xb8, 0x0c, 0x4a, 0xd2, 0x16, 0x23,
	0x16, 0xa5, 0x3b, 0x7f, 0x33, 0xf3, 0xfd, 0xcc, 0x48, 0x86, 0xbf, 0xa9, 0x92, 0x24, 0x72, 0x59,
	0xa2, 0x34, 0x49, 0xa5, 0x95, 0x51, 0xec, 0x38, 0x7d, 0x4d, 0x72, 0x95, 0x94, 0x22, 0xd5, 0x8a,
	0x50, 0xaf, 0x45, 0x8a, 0x94, 0x58, 0x63, 0xf1, 0x9b, 0x03, 0xc1, 0xfc, 0x0b, 0xb3, 0x31, 0xf4,
	0x44, 0x16, 0x3a, 0x91, 0x33, 0xf5, 0x79, 0x4f, 0x64, 0x2c, 0x82, 0x20, 0x43, 0x4a, 0xb5, 0xa8,
	0x8c, 0x50, 0x32, 0xec, 0xb5, 0x0d, 0xbb, 0xc4, 0xfe, 0x81, 0xfb, 0x8c, 0x22, 0x7f, 0x34, 0x61,
	0x3f, 0x72, 0xa6, 0x43, 0xbe, 0x41, 0xec, 0x06, 0x20, 0x55, 0xd2, 0x2c, 0x85, 0x44, 0x4d, 0xe1,
	0x20, 0xea, 0x4f, 0x83, 0xd9, 0x69, 0xb2, 0x27, 0x4f, 0x32, 0xdf, 0x52, 0xb8, 0xc5, 0x66, 0x13,
	0xf0, 0xd7, 0x48, 0x84, 0xc5, 0x83, 0xc8, 0xc2, 0x61, 0x9b, 0xc1, 0xeb, 0x0a, 0x8b, 0x2c, 0x16,
	0xe0, 0xef, 0x58, 0x3f, 0xf2, 0x4f, 0xc0, 0x4f, 0x6b, 0x32, 0xaa, 0x6c, 0x98, 0x5d, 0x7a, 0xaf,
	0x2b, 0x2c, 0xb2, 0x26, 0xba, 0xd2, 0x22, 0x17, 0xb2, 0x8d, 0xee, 0xf3, 0x0d, 0x62, 0xff, 0xe1,
	0x4f, 0x4d, 0xa8, 0x1b, 0xca, 0xa0, 0x6b, 0x34, 0x70, 0x91, 0xc5, 0xef, 0x0e, 0x78, 0x1c, 0xa9,
	0x52, 0x92, 0xb0, 0x61, 0x6b, 0xa4, 0xba, 0x30, 0xad, 0x9d, 0xc7, 0x37, 0x88, 0xdd, 0x42, 0x60,
	0x6d, 0xd4, 0x9a, 0x06, 0xb3, 0xb3, 0xdf, 0x6c, 0xbe, 0x7d, 0x73, 0x5b, 0x80, 0xdd, 0xc1, 0xc8,
	0x82, 0x14, 0xf6, 0xdb, 0x53, 0x1e, 0x26, 0xf8, 0x4d, 0x21, 0x1e, 0xc3, 0xe8, 0xaa, 0xac, 0xcc,
	0x0b, 0xc7, 0xa7, 0x1a, 0xc9, 0xcc, 0x3e, 0x1c, 0x60, 0xd6, 0xf4, 0x7d, 0xa7, 0xc6, 0x96, 0xe0,
	0xce, 0x35, 0x2e, 0x0d, 0xb2, 0x83, 0xcc, 0x8e, 0x4e, 0xf6, 0x4e, 0xef, 0x6e, 0xb8, 0x02, 0xf7,
	0x1a, 0xcd, 0x65, 0x51, 0xb0, 0xf3, 0xbd, 0x24, 0x3b, 0xf2, 0x01, 0x1e, 0x2b, 0xb7, 0xfd, 0x0a,
	0x17, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x11, 0xaf, 0x07, 0x1a, 0x1f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsignmentServiceClient is the client API for ConsignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsignmentServiceClient interface {
	Create(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
}

type consignmentServiceClient struct {
	cc *grpc.ClientConn
}

func NewConsignmentServiceClient(cc *grpc.ClientConn) ConsignmentServiceClient {
	return &consignmentServiceClient{cc}
}

func (c *consignmentServiceClient) Create(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cz.go.microservices.consignment.ConsignmentService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentServiceClient) GetAll(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/cz.go.microservices.consignment.ConsignmentService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsignmentServiceServer is the server API for ConsignmentService service.
type ConsignmentServiceServer interface {
	Create(context.Context, *Consignment) (*Response, error)
	GetAll(context.Context, *EmptyRequest) (*Response, error)
}

func RegisterConsignmentServiceServer(s *grpc.Server, srv ConsignmentServiceServer) {
	s.RegisterService(&_ConsignmentService_serviceDesc, srv)
}

func _ConsignmentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsignmentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz.go.microservices.consignment.ConsignmentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsignmentServiceServer).Create(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsignmentService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsignmentServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz.go.microservices.consignment.ConsignmentService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsignmentServiceServer).GetAll(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsignmentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cz.go.microservices.consignment.ConsignmentService",
	HandlerType: (*ConsignmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ConsignmentService_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ConsignmentService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consignment.proto",
}
