// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel.proto

package cz_go_microservices_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c0e45ee319d513, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Request) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c0e45ee319d513, []int{1}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Response struct {
	Vessel               *Vessel  `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c0e45ee319d513, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "cz.go.microservices.vessel.Request")
	proto.RegisterType((*Vessel)(nil), "cz.go.microservices.vessel.Vessel")
	proto.RegisterType((*Response)(nil), "cz.go.microservices.vessel.Response")
}

func init() { proto.RegisterFile("vessel.proto", fileDescriptor_e0c0e45ee319d513) }

var fileDescriptor_e0c0e45ee319d513 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x6c, 0xd3, 0x64, 0xac, 0x1e, 0xe6, 0x14, 0x83, 0x42, 0x89, 0x1e, 0x7a, 0xda,
	0x43, 0xbd, 0x79, 0x13, 0x44, 0xf1, 0xba, 0x82, 0xe2, 0xa9, 0x6c, 0x93, 0xa1, 0xae, 0x24, 0xd9,
	0x98, 0x5d, 0xd3, 0xea, 0xaf, 0xf1, 0xa7, 0x0a, 0xb3, 0xa5, 0xa2, 0x60, 0x6e, 0x99, 0x97, 0xf7,
	0x3e, 0xde, 0xcc, 0xc2, 0xb4, 0x27, 0x6b, 0xa9, 0x12, 0x6d, 0x67, 0x9c, 0xc1, 0xac, 0xf8, 0x14,
	0x6b, 0x23, 0x6a, 0x5d, 0x74, 0xc6, 0x52, 0xd7, 0xeb, 0x82, 0xac, 0xf0, 0x8e, 0xfc, 0x06, 0x26,
	0x92, 0xde, 0xde, 0xc9, 0x3a, 0xcc, 0x20, 0x2e, 0x54, 0xab, 0x0a, 0xed, 0x3e, 0xd2, 0x60, 0x16,
	0xcc, 0xc7, 0x72, 0x3f, 0xe3, 0x19, 0x40, 0xad, 0xb6, 0xcb, 0x0d, 0xe9, 0xf5, 0x8b, 0x4b, 0x43,
	0xfe, 0x9b, 0xd4, 0x6a, 0xfb, 0xc4, 0x42, 0xfe, 0x15, 0x40, 0xf4, 0xc8, 0x40, 0x3c, 0x86, 0x50,
	0x97, 0x9c, 0x4f, 0x64, 0xa8, 0xcb, 0x5f, 0xd4, 0x70, 0x90, 0x7a, 0xf0, 0x87, 0x8a, 0x08, 0xa3,
	0x46, 0xd5, 0x94, 0x8e, 0x18, 0xc6, 0xdf, 0x78, 0x0a, 0x89, 0xea, 0x95, 0xae, 0xd4, 0xaa, 0xa2,
	0x74, 0x3c, 0x0b, 0xe6, 0xb1, 0xfc, 0x11, 0xf0, 0x04, 0x62, 0xb3, 0x69, 0xa8, 0x5b, 0xea, 0x32,
	0x8d, 0x38, 0x35, 0xe1, 0xf9, 0xbe, 0xcc, 0x6f, 0x21, 0x96, 0x64, 0x5b, 0xd3, 0x58, 0xc2, 0x2b,
	0x88, 0xfc, 0xfa, 0xdc, 0xf3, 0x70, 0x91, 0x8b, 0xff, 0x2f, 0x24, 0xfc, 0x5e, 0x72, 0x97, 0x58,
	0xbc, 0xc2, 0x91, 0x57, 0x1e, 0xbc, 0x0f, 0x9f, 0x61, 0x7a, 0x47, 0xee, 0x7a, 0xdf, 0xe1, 0x7c,
	0x08, 0xb6, 0xbb, 0x75, 0x76, 0x31, 0x6c, 0xf2, 0x3d, 0x57, 0x11, 0xbf, 0xdf, 0xe5, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x6b, 0x65, 0x13, 0xc9, 0xcf, 0x01, 0x00, 0x00,
}
